=== Seventyy/xml/testing/xml_task_2_yes/xml_task_2.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="steam">
    <xs:complexType>
      <xs:sequence>
        
        
        
        
        <xs:element name="developers">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="developer" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="origin"/>
                    <xs:element type="xs:short" name="founding_year"/>
                    <xs:element type="xs:short" name="employee_count"/>
                    <xs:element type="xs:boolean" name="independent"/>
                    <xs:element type="xs:string" name="phone"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="developer_id"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>






        <xs:element name="games">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="game" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="title"/>
                    <xs:element type="xs:dateTime" name="release_date"/>
                    <xs:element name="size">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:float">
                            <xs:attribute type="xs:string" name="unit"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="price">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:float">
                            <xs:attribute type="xs:string" name="currency"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="games:review_score" name="steam_reviews"/>
                    <xs:element type="xs:integer" name="review_count"/>
                    <xs:element type="xs:string" name="genre"/>
                    <xs:element name="licence">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="type"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="game_id"/>
                  <xs:attribute type="xs:string" name="developer_id"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:simpleType name="review_score" final="restriction" >
          <xs:restriction base="xs:string">                            
            <xs:enumeration value="Overhwelmingly Positive" />
            <xs:enumeration value="Very Positive" />
            <xs:enumeration value="Positive" />
            <xs:enumeration value="Mostly Positive" />
            <xs:enumeration value="Mixed" />
            <xs:enumeration value="Mostly Negative" />
            <xs:enumeration value="Negative" />
            <xs:enumeration value="Very Negative" />
            <xs:enumeration value="Overwhelmingly Negative" />
          </xs:restriction>
        </xs:simpleType>


      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Seventyy/xml/xml_task_2/xml_task_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="xml_task_2.css"?>
<steam xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="xml_task_2.xsd"
xmlns:developers="http://developers.com"
xmlns:games="http://games.com">
	<developers>
		<developers:developer developer_id="D1">
			<name>Ninja Kiwi</name>            
			<origin>New Zealand</origin>        
			<founding_year>2006</founding_year>
			<employee_count>70</employee_count>
			<independent>false</independent>  
			<phone>+64 123 456 789</phone>           
		</developers:developer>
		<developers:developer developer_id="D2">
			<name>CD Project</name>            
			<origin>Poland</origin>        
			<founding_year>1994</founding_year>
			<employee_count>1111</employee_count>
			<independent>false</independent>  
			<phone>+48 273 829 178</phone>           
		</developers:developer>
		<developers:developer developer_id="D3">
			<name>Supergiant Games</name>            
			<origin>USA</origin>        
			<founding_year>2009</founding_year>
			<employee_count>20</employee_count>
			<independent>false</independent>  
			<phone>+1 235 627 128</phone>           
		</developers:developer>
		<developers:developer developer_id="D4">
			<name>Valve</name>            
			<origin>USA</origin>        
			<founding_year>1996</founding_year>
			<employee_count>360</employee_count>
			<independent>false</independent>  
			<phone>+1 321 454 645</phone>           
		</developers:developer>
	</developers>
	<games>
		<games:game game_id="G1" developer_id="D1">
			<title>Bloons TD 6</title>                                 
			<release_date>2018-12-18</release_date>                      
			<size unit="GB">2.6</size>
			<price currency="PLN">34.99</price>                        
			<steam_reviews>Overhwelmingly Positive</steam_reviews>     
			<review_count>9347</review_count>                          
			<genre>Tower Defence</genre>                               
			<licence type="proprietary"/>                              
		</games:game>
		<games:game game_id="G2" developer_id="D1">
			<title>Bloons TD Battles 2</title>                                 
			<release_date>2020-11-09</release_date>                      
			<size unit="GB">5.2</size>                                 
			<price currency="PLN">0.0</price>                        
			<steam_reviews>Mostly Positive</steam_reviews>     
			<review_count>12213</review_count>                          
			<genre>Tower Defence</genre>                               
			<licence type="proprietary"/>                              
		</games:game>
		<games:game game_id="G3" developer_id="D1">
			<title>Bloons Monkey City</title>                                 
			<release_date>2014-12-04</release_date>                      
			<size unit="GB">1.3</size>                                 
			<price currency="PLN">0.0</price>                        
			<steam_reviews>Very Positive</steam_reviews>     
			<review_count>1623</review_count>                          
			<genre>Tower Defence</genre>                               
			<licence type="proprietary"/>                              
		</games:game>
		<games:game game_id="G4" developer_id="D1">
			<title>SAS: Zombie Assault 4</title>                                 
			<release_date>2017-08-16</release_date>                      
			<size unit="GB">2.8</size>                                 
			<price currency="PLN">0.0</price>                        
			<steam_reviews>Very Positive</steam_reviews>     
			<review_count>3623</review_count>                          
			<genre>Twin-Stick Shooter</genre>                               
			<licence type="proprietary"/>                              
		</games:game>
		<games:game game_id="G5" developer_id="D1">
			<title>Bloons Adventure Time TD</title>                                 
			<release_date>2019-07-16</release_date>                      
			<size unit="GB">3.9</size>                                 
			<price currency="PLN">0.0</price>                        
			<steam_reviews>Very Positive</steam_reviews>     
			<review_count>1665</review_count>                          
			<genre>Tower Defence</genre>                               
			<licence type="proprietary"/>                              
		</games:game>		
        <games:game game_id="G6" developer_id="D2">
			<title>The Witcher 3: Wild Hunt</title>                                 
			<release_date>2015-05-18</release_date>                      
			<size unit="GB">58.9</size>                                 
			<price currency="PLN">99.99</price>                        
			<steam_reviews>Overhwelmingly Positive</steam_reviews>     
			<review_count>181234</review_count>                          
			<genre>RPG</genre>                               
			<licence type="proprietary"/>                              
		</games:game>	
        <games:game game_id="G7" developer_id="D2">
			<title>Cyberpunk 2077</title>                                 
			<release_date>2020-12-10</release_date>                      
			<size unit="GB">78.6</size>                                 
			<price currency="PLN">199.99</price>                        
			<steam_reviews>Mostly Positive</steam_reviews>     
			<review_count>230421</review_count>                          
			<genre>RPG</genre>                               
			<licence type="proprietary"/>                              
		</games:game>
        <games:game game_id="G8" developer_id="D2">
			<title>Thronebreaker: The Witcher Tales</title>                                 
			<release_date>2018-11-09</release_date>                      
			<size unit="GB">12.3</size>                                 
			<price currency="PLN">79.99</price>                        
			<steam_reviews>Very Positive</steam_reviews>     
			<review_count>3235</review_count>                          
			<genre>RPG</genre>                               
			<licence type="proprietary"/>                              
		</games:game>
        <games:game game_id="G9" developer_id="D2">
			<title>GWENT: The Witcher Card games:game</title>                                 
			<release_date>2020-05-19</release_date>                      
			<size unit="GB">9.8</size>                                 
			<price currency="PLN">0.0</price>                        
			<steam_reviews>Very Positive</steam_reviews>     
			<review_count>13235</review_count>                          
			<genre>Card games:game</genre>                               
			<licence type="proprietary"/>
		</games:game>
        <games:game game_id="G10" developer_id="D2">
			<title>The Witcher 2: Assassins of Kings</title>                                 
			<release_date>2011-05-17</release_date>                      
			<size unit="GB">9.6</size>                                 
			<price currency="PLN">39.99</price>                        
			<steam_reviews>Very Positive</steam_reviews>     
			<review_count>23432</review_count>                          
			<genre>RPG</genre>                               
			<licence type="proprietary"/>
		</games:game>
        <games:game game_id="G11" developer_id="D2">
			<title>The Witcher</title>                                 
			<release_date>2008-09-16</release_date>                      
			<size unit="GB">4.2</size>                                 
			<price currency="PLN">29.99</price>                        
			<steam_reviews>Very Positive</steam_reviews>     
			<review_count>19203</review_count>                          
			<genre>RPG</genre>                               
			<licence type="proprietary"/>
		</games:game>
        <games:game game_id="G12" developer_id="D3">
			<title>Bastion</title>                                 
			<release_date>2011-08-16</release_date>                      
			<size unit="GB">6.3</size>                                 
			<price currency="PLN">53.99</price>                        
			<steam_reviews>Overhwelmingly Positive</steam_reviews>     
			<review_count>22803</review_count>                          
			<genre>Action</genre>                               
			<licence type="proprietary"/>
		</games:game>
        <games:game game_id="G13" developer_id="D3">
			<title>Transistor</title>                                 
			<release_date>2014-05-20</release_date>                      
			<size unit="GB">7.4</size>                                 
			<price currency="PLN">71.99</price>                        
			<steam_reviews>Very Positive</steam_reviews>     
			<review_count>16802</review_count>                          
			<genre>Action</genre>                               
			<licence type="proprietary"/>
		</games:game>
        <games:game game_id="G14" developer_id="D3">
			<title>Pyre</title>                                 
			<release_date>2017-06-25</release_date>                      
			<size unit="GB">12.3</size>                                 
			<price currency="PLN">71.99</price>                        
			<steam_reviews>Very Positive</steam_reviews>     
			<review_count>5199</review_count>                          
			<genre>Action</genre>                               
			<licence type="proprietary"/>
		</games:game>
        <games:game game_id="G15" developer_id="D3">
			<title>Hades</title>                                 
			<release_date>2020-09-17</release_date>                      
			<size unit="GB">15.7</size>                                 
			<price currency="PLN">89.99</price>                        
			<steam_reviews>Overhwelmingly Positive</steam_reviews>     
			<review_count>7893</review_count>                          
			<genre>Roguelike</genre>                               
			<licence type="proprietary"/>
		</games:game>
        <games:game game_id="G16" developer_id="D4">
			<title>Portal 2</title>
